# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InstaApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InstaApp
	pod 'Parse'
	pod 'MBProgressHUD'
  target 'InstaAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InstaAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
